DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `getData`()
CREATE TABLE TABLE_C (
SELECT A.ID, A.CARDNUMBER, A.ISS, A.ACQ, A.DEST, A.STATUS AS STATUS_A, B.STATUS AS STATUS_ISS, A.STATUS AS STATUS_ACQ, B.STATUS AS STATUS_DEST
FROM TABLE_A A
JOIN TABLE_B B 
ON A.ID = B.ID
WHERE B.STATUS = 0
)$$
DELIMITER ;
